### ISSUE TITLE
Implement MVP

### ISSUE THREAD

**Issue by aazuspan** [alxmrs/dask-ee#1]
As discussed in google/Xee#153, I'll put together a PR with the core functionality of loading Earth Engine data into a Dask dataframe via a top-level `read_ee` function.

We settled on `dask-geopandas` as an optional dependency to enable geospatial processing on deferred dataframes, but I'm leaning towards omitting that from the MVP until geopandas/dask-geopandas#285 is merged. The alternative would be to pin to an older Dask before the incompatible query planning system was added or disable query planning in the [Dask configuration](https://dask-geopandas.readthedocs.io/en/stable/docs/reference/api/dask_geopandas.from_dask_dataframe.html#dask_geopandas.from_dask_dataframe). Given that there's a fix in progress, I'm in favor of just postponing that feature until it's released and then pinning to that.

That doesn't stop us from optionally using GeoDataFrames for the underlying chunks in the Dask dataframe, and if a user *needs* to run geospatial operations without computing they can always set their own Dask config and wrap the `read_ee` output in [`from_dask_dataframe`](https://dask-geopandas.readthedocs.io/en/stable/docs/reference/api/dask_geopandas.from_dask_dataframe.html#dask_geopandas.from_dask_dataframe).

Let me know if you have strong feelings on that @alxmrs - otherwise I'll move ahead with that plan.

**Comment by alxmrs** [comment]
That plan sounds correct. Thanks for looking into the limitation, I wasn’t aware.

**Comment by aazuspan** [comment]
Sorry for dropping the ball on this - got tied up with other projects. Glad to see it come together!

**Comment by alxmrs** [comment]
No problem at all! Thanks!
